### ISSUE TITLE
Using one cassete per test class

### ISSUE THREAD

**Issue by pawelad** [ktosiek/pytest-vcr#4]
Hiya,

Thanks for the plugin, I like it a lot.  One thing that I'm wondering if it's possible / worth doing is allowing marked classes to use one cassete, so:

```python
@pytest.mark.vcr()
def test_foo():
    pass

@pytest.mark.vcr()
def test_bar():
    pass
```

would create `test_foo.yaml` and `test_bar.yaml` as you'd expect, but:

```python
@pytest.mark.vcr()
class TestFoobar:
    def test_foo(self):
        pass

    def test_bar(self):
        pass
```

would only create one cassete `TestFoobar.yaml` instead of `TestFoobar.test_foo.yaml` and `TestFoobar.test_bar.yaml`.

I don't know if that's even possible re py.test and vcr.py but wanted to ask, as it would make sense in my use case when I'm class is a group of tests of one function (which does one external request) but with different parameter.

**Comment by pawelad** [comment]
I actually managed to do that locally, although I'm still wondering if that's actually a good practice. Let me know what you think, I'm happy to do a PR if you think it's worth it.

**Comment by ktosiek** [comment]
I'll try to look at that later today. For now you should be able to get the behaviour you want by overriding the [vcr_cassette_name](http://pytest-vcr.readthedocs.io/en/latest/configuration/#vcr_cassette_name) fixture.

**Comment by ktosiek** [comment]
Also, that would use the same file twice - so it would only work if all those tests make the same set of requests. It would be harder to have a cassette that spans multiple tests without being reinitialized (still possible with pytest class-scoped fixtures, but that would change the plugin's API a bit).

**Comment by pawelad** [comment]
> For now you should be able to get the behaviour you want by overriding the vcr_cassette_name fixture.
Yeah, you're right, that's basically what I did [here](https://github.com/pawelad/pytest-vcr/commit/28b8e78cf8b141b5e00d57ef10e5110ed7f62ad1) with an additional config argument - thanks!

> Also, that would use the same file twice - so it would only work if all those tests make the same set of requests.

That's my exact use case but I wonder how often that is and if that's actually a good practice and worth implementing into the plugin.

**Comment by ktosiek** [comment]
I don't see this being common, but I'll leave the issue open for now, so if anyone else has a similar use-case they can leave a comment.

For integrating this in the plugin I'd also have to look at how VCR.py behaves when multiple tests are trying to create the same file (with xdist).
