### ISSUE TITLE
Is it possible to access the cassette from within the test?

### ISSUE THREAD

**Issue by fiveohhh** [ktosiek/pytest-vcr#9]
I want to gain access to `cass.all_played` (https://github.com/kevin1024/vcrpy/blob/master/docs/advanced.rst).  Is this possible with pytest-vcr?

**Comment by ktosiek** [comment]
there's a {{vcr_cassette}} fixture with the current cassette, maybe that'll work?

**Comment by ktosiek** [comment]
Closing the issue, as I believe the functionality is already available.

**Comment by dokuboyejo** [comment]
@ktosiek any pointers as to how the functionality is used ... couldn't get it from the docs
Essentially, to know how to access the cassette object

**Comment by samamorgan** [comment]
I'm stuck here too. I want to check the number of requests made, and can't figure out how to access the cassette. @ktosiek can you show some example code of how this is done?

Running in a debugger, I see no vcr or cassette instance in locals or globals.

**Comment by ktosiek** [comment]
An example of using the `vcr_cassette` fixture would be:

```python
import pytest
from urllib.request import urlopen

@pytest.mark.vcr()
def test_google(vcr_cassette):
    response = urlopen('http://www.iana.org/domains/reserved').read()
    assert vcr_cassette.all_played
```

You get access to a fixture by adding it's name as your test's argument.
